<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ScriptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $scripts = [
            [
                'id' => 1,
                'title' => "Advanced Police System",
                'description' => "Complete police management system with MDT, evidence tracking, and integrated dispatch.",
                'price' => 49.99,
                'category' => "Police",
                'rating' => 4.9,
                'image' => "https://images.pexels.com/photos/3846022/pexels-photo-3846022.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => true,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'title' => "Economy Framework Pro",
                'description' => "Comprehensive economy system with jobs, banking, properties, and businesses.",
                'price' => 79.99,
                'category' => "Jobs & Economy",
                'rating' => 4.8,
                'image' => "https://images.pexels.com/photos/730547/pexels-photo-730547.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => true,
                'isOnSale' => true,
                'discount' => 25,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'title' => "Immersive HUD Bundle",
                'description' => "Fully customizable HUD with speed, fuel, health, armor, and mini-map integration.",
                'price' => 29.99,
                'category' => "UI/HUD",
                'rating' => 4.7,
                'image' => "https://images.pexels.com/photos/4257766/pexels-photo-4257766.jpeg",
                'video' => null,
                'isNew' => true,
                'isFeatured' => true,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'title' => "Street Racing System",
                'description' => "Complete racing system with custom tracks, leaderboards, and betting.",
                'price' => 39.99,
                'category' => "Racing",
                'rating' => 4.8,
                'image' => "https://images.pexels.com/photos/1335077/pexels-photo-1335077.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => true,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'title' => "Advanced Inventory System",
                'description' => "Feature-rich inventory system with drag-and-drop, item crafting, and weight management.",
                'price' => 54.99,
                'category' => "Roleplay",
                'rating' => 4.6,
                'image' => "https://images.pexels.com/photos/2240571/pexels-photo-2240571.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'title' => "Dynamic Weather System",
                'description' => "Realistic weather patterns with visual effects, affecting vehicle handling and gameplay.",
                'price' => 19.99,
                'category' => "Roleplay",
                'rating' => 4.3,
                'image' => "https://images.pexels.com/photos/1431822/pexels-photo-1431822.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => true,
                'discount' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'title' => "Advanced Admin Panel",
                'description' => "Comprehensive admin panel with player management, reports, and server monitoring.",
                'price' => 44.99,
                'category' => "Admin Tools",
                'rating' => 4.9,
                'image' => "https://images.pexels.com/photos/6963944/pexels-photo-6963944.jpeg",
                'video' => null,
                'isNew' => true,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'title' => "Custom Vehicle Shop",
                'description' => "Feature-rich vehicle shop with test drives, financing, and customization.",
                'price' => 34.99,
                'category' => "Vehicles",
                'rating' => 4.7,
                'image' => "https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'title' => "EMS Medical System",
                'description' => "Complete medical system with injuries, treatments, and hospital management.",
                'price' => 49.99,
                'category' => "EMS",
                'rating' => 4.8,
                'image' => "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'title' => "Criminal Activities Bundle",
                'description' => "Complete package for robberies, heists, and illegal activities with progression system.",
                'price' => 69.99,
                'category' => "Roleplay",
                'rating' => 4.5,
                'image' => "https://images.pexels.com/photos/2882566/pexels-photo-2882566.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => true,
                'discount' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'title' => "Custom Weapon Framework",
                'description' => "Advanced weapon system with attachments, durability, and custom animations.",
                'price' => 39.99,
                'category' => "Weapons",
                'rating' => 4.6,
                'image' => "https://images.pexels.com/photos/2495555/pexels-photo-2495555.jpeg",
                'video' => null,
                'isNew' => true,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'title' => "Phone System Pro",
                'description' => "Feature-rich phone system with apps, messaging, calling, and social media.",
                'price' => 59.99,
                'category' => "UI/HUD",
                'rating' => 4.9,
                'image' => "https://images.pexels.com/photos/7821486/pexels-photo-7821486.jpeg",
                'video' => null,
                'isNew' => false,
                'isFeatured' => false,
                'isOnSale' => false,
                'discount' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('scripts')->insert($scripts);
    }
}
